clinical = read.csv("clinical_trial.csv", stringsAsFactors = FALSE)
max(nchar(clinical$abstract))
nchar(as.vector(clinical$abstract[476]))
str(clinical)
count =0
sum(nchar(clinical$abstract) == 0)
which.min(nchar(clinical$title))
clinical$title[1258]
corpusTitle = Corpus(VectorSource(clinical$title))
corpusAbstract = Corpus(VectorSource(clinical$abstract))
corpusTitle = tm_map(corpusTitle, tolower)
corpusTitle = tm_map(corpusTitle, removePunctuation)
corpusTitle = tm_map(corpusTitle, removeWords,stopwords("english"))
corpusTitle = tm_map(corpusTitle, stemDocument)
dtmTitle = DocumentTermMatrix(corpusTitle)
sparseTitle = removeSparseTerms(dtmTitle,.95)
dtmTitle = as.data.frame(as.matrix(sparseTitle))
corpusAbstract = tm_map(corpusAbstract, tolower)
corpusAbstract = tm_map(corpusAbstract, removePunctuation)
corpusAbstract = tm_map(corpusAbstract, removeWords,stopwords("english"))
corpusAbstract = corpusAbstract = tm_map(corpusAbstract, stemDocument)
dtmAbstract = DocumentTermMatrix(corpusAbstract)
dtmAbstract=removeSparseTerms(dtmAbstract,.95)
dtmAbstract = as.data.frame(as.matrix(dtmAbstract))
dim(dtmTitle)
dim(dtmAbstract)
sort(colSums(dtmAbstract))
csAbstract = colSums(dtmAbstract)
which.max(csAbstract)
colnames(dtmTitle) = paste0("T",colnames(dtmTitle))
colnames(dtmAbstract) =paste0("A",colnames(dtmAbstract))
dtm = cbind(dtmTitle,dtmAbstract)
dtm$trial = clinical$trial
set.seed(144)
split = sample.split(dtm$trial,0.7)
train = subset(dtm,split==TRUE)
test = subset(dtm,split==FALSE)
table(train$trial)
730/nrow(train)
trialCart = rpart(trial~.,data=train,method = "class")
prp(trialCart)
predTrain =predict(trialCart)[,2]
summary(predTrain)
predTrain1 = predict(trialCart,type = "class")
table(train$trial,predTrain1)
accuracy =(631+441)/nrow(train)
sensitivity= 441/(131+441)
specificity =631/(631+99)
predTrial = predict(trialCart, newdata=test)[,2]
table(test$trial, predTest >= 0.5)
predRocr = prediction(predTrial,test$trial)
auc = as.numeric(performance(predRocr,"auc")@y.values)
